version: '3.8'

services:
  postgres:
    image: postgres:16
    container_name: ms-scheduling-db
    environment:
      POSTGRES_DB: ms-scheduling
      POSTGRES_USER: postgres-user
      POSTGRES_PASSWORD: postgres-password
    ports:
      - "5436:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data
volumes:
  pgdata: