spring:
  application:
    name: email

  datasource:
    url: jdbc:postgresql://localhost:5433/ms-email
    username: postgres
    password: postgres
    driver-class-name: org.postgresql.Driver

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialectPostgreSQLDialect

server:
  port: 8080